title: Life as it happens
description: My Personal Life
author: Rohit Gupta
github: https://github.com/krullun
about: I am Machine Learning enthusiast.
disqus_shortname: mainpage
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/krullun"
    - icon: fa-twitter
      link: "https://twitter.com/krullun"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/krullun"
    - icon: fa-goodreads
      link: "https://www.goodreads.com/krullun"
    - icon: fa-github
      link: "https://github.com/krullun"

share:
  twitter_username: krullun
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://krullun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
